# fly.toml app configuration file generated for prisma-genius on 2024-01-03T12:46:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prisma-genius"
primary_region = "bos"

[build]

[http_service]
  internal_port = 8080
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
